title: Ron Huang
url: http://ronhuang.org
description: 'Personal site of Ron Huang, PhD student and software programmer from Taiwan'
keywords:
 - Ron Huang
 - Yih-Lun Huang
 - ronhuang
 - 黃翊倫

author:
    name: Ron Huang
    email: ronhuang@gmail.com
    twitter: ronhuang
    github: ronhuang
    delicious: ronhuang
    facebook: ronhuang
    feedburner: ronhuang
    avatar: http://www.gravatar.com/avatar/5c3e79143f33d4dd83ad471742705fe4?s=70
    openid:
        server: https://www.google.com/accounts/o8/ud
        delegate: http://www.google.com/profiles/ronhuang

sections:
 - projects
 - about
 - journal
projects:
 - steamy
colors:
    mono:
        dark: '#111122'
        medium: '#555555'
        light: '#CCCCBB'
    bg: '#EAF1F4'

pygments: true
permalink: pretty
exclude:
 - Rakefile
 - README.markdown
 - .git
 - static
markdown: kramdown
