baseurl = "https://ron.hng.tw/"
languageCode = "zh-TW"
hasCJKLanguage = true
title = "Ron Huang"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
disqusShortname = "ronhuang"
paginate = 5
theme = "casper"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "I am a software developer from Taiwan"
  cover = "/img/cover.jpg"
  author = "Ron Huang"
  authorlocation = "Taipei, Taiwan"
  authorwebsite = "https://ron.hng.tw/"
  bio = "Father, software developer, HP Inc. engineer, and Star Wars fan."
  logo = "/img/logo.png"
  githubName = "ronhuang"
  twitterName = "ronhuang"
  linkedinName = "ronhuang"
  mastodonProfile = "https://g0v.social/@ronhuang"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
